include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Предпочтительно использовать одинарные кавычки для строковых литералов.
    prefer_single_quotes: true

    # Требовать запятые в конце строк там, где это применимо (в списках параметров и т. д.).
    require_trailing_commas: true

    # Предпочтительно использовать конструкторы const, где это возможно.
    prefer_const_constructors: true

    # Рекомендует использовать const литералы при создании неизменяемых объектов.
    prefer_const_literals_to_create_immutables: true

    # Рекомендует использовать const конструкторы в неизменяемых классах.
    prefer_const_constructors_in_immutables: true

    # Предпочтительно объявлять поля как final, где это возможно.
    prefer_final_fields: true

    # Рекомендует объявлять локальные переменные как final, если их значение не меняется.
    prefer_final_locals: true

    # Рекомендует использовать const для объявлений переменных, если значение известно на этапе компиляции.
    prefer_const_declarations: true

    # Рекомендует использовать стрелочные функции (=>) для однострочных функций.
    prefer_expression_function_bodies: true

    # Рекомендует использовать if элементы в коллекциях вместо тернарных операторов.
    prefer_if_elements_to_conditional_expressions: false

    # Рекомендует использовать оператор ?? вместо if (x == null).
    prefer_if_null_operators: true

    # Рекомендует использовать ??= вместо if (x == null) x = y.
    prefer_conditional_assignment: true

    # Рекомендует использовать литералы коллекций ([], {}) вместо конструкторов.
    prefer_collection_literals: true

    # Рекомендует использовать смежные строки вместо + для конкатенации.
    prefer_adjacent_string_concatenation: true

    # Рекомендует использовать интерполяцию строк ($variable) вместо конкатенации.
    prefer_interpolation_to_compose_strings: true

    # Рекомендует встраивать элементы в литерал вместо использования add()/addAll().
    prefer_inlined_adds: true

    # Рекомендует использовать .contains() вместо .indexOf() != -1.
    prefer_contains: true

    # Рекомендует использовать .isEmpty / .isNotEmpty вместо сравнения с длиной.
    prefer_is_empty: true
    prefer_is_not_empty: true

    # Рекомендует использовать .forEach() вместо циклов for для простых операций.
    prefer_foreach: true

    # Рекомендует использовать for элементы в коллекциях вместо map().
    prefer_for_elements_to_map_fromIterable: true

    # Рекомендует объявлять функции как void function() вместо void Function() variable.
    prefer_function_declarations_over_variables: true

    # Рекомендует использовать generic типы функций вместо typedef.
    prefer_generic_function_type_aliases: true

    # Рекомендует использовать инициализирующие формальные параметры (this.field) вместо присваиваний в теле конструктора.
    prefer_initializing_formals: true

    # Рекомендует использовать целочисленные литералы вместо double литералов, когда возможно.
    prefer_int_literals: true

    # Рекомендует использовать final в циклах for-in.
    prefer_final_in_for_each: true

    # Рекомендует использовать конструкторы вместо статических методов для создания объектов.
    prefer_constructors_over_static_methods: true

    # Рекомендует размещать assert в списке инициализаторов, а не в теле конструктора.
    prefer_asserts_in_initializer_lists: true

    # Рекомендует добавлять сообщения в assert для лучшей отладки.
    prefer_asserts_with_message: true

    # ???
    # Рекомендует опускать типы локальных переменных, когда они могут быть выведены.
    omit_local_variable_types: false

    # ???
    # Рекомендует опускать очевидные типы свойств.
    omit_obvious_property_types: false

    # Предупреждает об использовании BuildContext после асинхронных операций без проверки mounted.
    use_build_context_synchronously: true

    # Рекомендует использовать полные шестнадцатеричные значения для цветов Flutter.
    use_full_hex_values_for_flutter_colors: true

    # Рекомендует использовать key в конструкторах виджетов для лучшей производительности.
    use_key_in_widget_constructors: true

    # Рекомендует использовать rethrow вместо throw e для сохранения stack trace.
    use_rethrow_when_possible: true

    # Рекомендует использовать сеттеры для изменения свойств вместо методов.
    use_setters_to_change_properties: true

    # Рекомендует использовать StringBuffer для построения строк в циклах.
    use_string_buffers: true

    # Рекомендует использовать .to() и .as() методы, когда они доступны.
    use_to_and_as_if_applicable: true

    # Рекомендует использовать final для параметров.
    prefer_final_parameters: true

    # Рекомендует использовать null-aware операторы (?. ?? ??=).
    prefer_null_aware_operators: true

    # Рекомендует указывать типы для неинициализированных переменных.
    prefer_typing_uninitialized_variables: true

    # Рекомендует использовать void вместо Null.
    prefer_void_to_null: true

    # Рекомендует предоставлять сообщения при использовании @deprecated.
    provide_deprecation_message: true

    # Рекомендует использовать HTTPS для URL в pubspec.yaml.
    secure_pubspec_urls: true

    # Рекомендует использовать SizedBox.shrink и SizedBox.expand вместо Container.
    sized_box_shrink_expand: true

    # Рекомендует использовать ColoredBox вместо Container для цвета.
    use_colored_box: true

    # Рекомендует использовать DecoratedBox вместо Container для декорации.
    use_decorated_box: true

    # Рекомендует использовать синтаксис типов функций для параметров.
    use_function_type_syntax_for_parameters: true

    # Рекомендует использовать if (x != null) вместо if (x) для nullable (??).
    use_if_null_to_convert_nulls_to_bools: false

    # Рекомендует использовать .isEven вместо % 2 == 0.
    use_is_even_rather_than_modulo: true

    # Рекомендует использовать late для приватных полей и переменных.
    use_late_for_private_fields_and_variables: true

    # Рекомендует использовать именованные константы вместо магических чисел.
    use_named_constants: true

    # Рекомендует использовать super параметры.
    use_super_parameters: true

    # Рекомендует использовать matchers для throws в тестах.
    use_test_throws_matchers: true

    # Рекомендует использовать whereType для фильтрации по типу в коллекциях.
    prefer_iterable_whereType: true

    # Предупреждает о рекурсивных геттерах, которые могут привести к переполнению стека.
    recursive_getters: true

    # Предупреждает об избыточном использовании await в выражениях return.
    unnecessary_await_in_return: true

    # Предупреждает об избыточных проверках на null.
    unnecessary_null_checks: true

    # Предупреждает об избыточном использовании null в операторах ??.
    unnecessary_null_in_if_null_operators: true

    # Рекомендует избегать async когда await не используется.
    unnecessary_async: true

    # Рекомендует избегать избыточного использования const.
    unnecessary_const: true

    # Рекомендует избегать избыточных имен конструкторов.
    unnecessary_constructor_name: true

    # Рекомендует использовать tear-offs вместо лямбд, когда возможно.
    unnecessary_lambdas: true

    # Рекомендует избегать new перед конструкторами.
    unnecessary_new: true

    # Рекомендует избегать избыточных переопределений методов.
    unnecessary_overrides: true

    # Рекомендует избегать избыточных скобок.
    unnecessary_parenthesis: true

    # Рекомендует избегать избыточных raw строк.
    unnecessary_raw_strings: true

    # Рекомендует избегать ненужных операторов.
    unnecessary_statements: true

    # Рекомендует избегать избыточных экранирований в строках.
    unnecessary_string_escapes: true

    # Рекомендует избегать избыточной интерполяции строк.
    unnecessary_string_interpolations: true

    # Рекомендует избегать избыточного использования this..
    unnecessary_this: true

    # Рекомендует избегать избыточного использования unawaited().
    unnecessary_unawaited: true

    # Рекомендует добавлять @override при переопределении методов.
    annotate_overrides: true

    # Рекомендует добавлять @redeclare при переопределении полей.
    annotate_redeclares: true

    # Рекомендует избегать смежных строк в списках, использовать один литерал.
    no_adjacent_strings_in_list: true

    # Рекомендует избегать дублирующихся значений в switch case.
    no_duplicate_case_values: true

    # Рекомендует избегать логики в createState() методах Flutter.
    no_logic_in_create_state: true

    # Рекомендует избегать использования .runtimeType.toString().
    no_runtimeType_toString: true

    # Рекомендует избегать самоприсваиваний (x = x).
    no_self_assignments: true

    # Рекомендует избегать использования переменных с подстановочными знаками (_).
    no_wildcard_variable_uses: true

    # Рекомендует переопределять hashCode при переопределении ==.
    hash_and_equals: true

    # Рекомендует указывать конкретные типы исключений в catch.
    avoid_catches_without_on_clauses: true

    # Рекомендует не перехватывать Error и его подклассы, только Exception.
    avoid_catching_errors: true

    # Рекомендует не указывать возвращаемый тип для сеттеров (всегда void).
    avoid_return_types_on_setters: true

    # Рекомендует закрывать StreamController и IOSink после использования.
    close_sinks: true

    # Рекомендует обрабатывать все возвращаемые Future, чтобы не пропускать ошибки.
    discarded_futures: true

    # Рекомендует явно помечать Future, которые не ожидаются, используя unawaited().
    unawaited_futures: true

    # Рекомендует избегать пустых операторов (;).
    empty_statements: true

    # Рекомендует не переопределять == и hashCode в изменяемых классах.
    avoid_equals_and_hash_code_on_mutable_classes: true

    # Рекомендует избегать экранирования внутренних кавычек, используя альтернативные кавычки.
    avoid_escaping_inner_quotes: true

    # Рекомендует избегать инициализаторов полей в const классах.
    avoid_field_initializers_in_const_classes: true

    # Рекомендует использовать функции-члены вместо литералов в forEach.
    avoid_function_literals_in_foreach_calls: true

    # Рекомендует не инициализировать переменные значением null явно.
    avoid_init_to_null: true

    # Рекомендует избегать явных проверок на null в операторах равенства.
    avoid_null_checks_in_equality_operators: true

    # Рекомендует избегать позиционных булевых параметров; использовать именованные.
    avoid_positional_boolean_parameters: true

    # Рекомендует избегать приватных typedef для функций.
    avoid_private_typedef_functions: true

    # Рекомендует избегать избыточных значений аргументов (например, true для булевых параметров).
    avoid_redundant_argument_values: true

    # Рекомендует не возвращать null из функций с типом void.
    avoid_returning_null_for_void: true

    # Рекомендует избегать возврата this из методов (кроме паттерна builder).
    avoid_returning_this: true

    # Рекомендует не создавать сеттеры без соответствующих геттеров
    avoid_setters_without_getters: true

    # Рекомендует избегать затенения параметров типов.
    avoid_shadowing_type_parameters: true

    # Рекомендует избегать одиночных каскадов в выражениях.
    avoid_single_cascade_in_expression_statements: true

    # Рекомендует избегать медленных асинхронных операций I/O в критичных участках.
    avoid_slow_async_io: true

    # Рекомендует избегать использования .toString() для типов.
    avoid_type_to_string: true

    # Рекомендует избегать использования типов в качестве имен параметров.
    avoid_types_as_parameter_names: true

    # Рекомендует избегать ненужных Container виджетов в Flutter.
    avoid_unnecessary_containers: true

    # Рекомендует избегать неиспользуемых параметров конструкторов.
    avoid_unused_constructor_parameters: true

    # ???
    # Рекомендует опускать типы параметров замыканий, когда они очевидны.
    avoid_types_on_closure_parameters: false

    # Рекомендует избегать веб-библиотек в Flutter приложениях.
    avoid_web_libraries_in_flutter: true

    # Рекомендует использовать каскадные вызовы (..) для цепочки операций.
    cascade_invocations: true

    # Рекомендует избегать приведения nullable типов к non-nullable.
    cast_nullable_to_non_nullable: true

    # Рекомендует избегать методов коллекций с несовместимыми типами.
    collection_methods_unrelated_type: true

    # Рекомендует упорядочивать комбинаторы (show, hide) в импортах.
    combinators_ordering: true

    # Рекомендует проверять правильность ссылок в комментариях.
    comment_references: true

    # Рекомендует проверять существование условных URI.
    conditional_uri_does_not_exist: true

    # Рекомендует избегать управления потоком в блоках finally.
    control_flow_in_finally: true

    # Рекомендует избегать висячих документационных комментариев библиотек.
    dangling_library_doc_comments: true

    # ???
    # Рекомендует добавлять зависимости для всех используемых пакетов.
    depend_on_referenced_packages: true

    # Рекомендует использовать согласованные версии устаревших API.
    deprecated_consistency: true

    # Рекомендует избегать использования устаревших членов из того же пакета.
    deprecated_member_use_from_same_package: true

    # Рекомендует описывать все свойства в Diagnosticable классах.
    diagnostic_describe_all_properties: false

    # Рекомендует избегать использования do_not_use_environment.
    do_not_use_environment: true

    # ???
    # Рекомендует документировать причины игнорирования правил.
    document_ignores: false

    # Рекомендует добавлять символ новой строки в конце файла.
    eol_at_end_of_file: true

    # Рекомендует обеспечивать исчерпывающие case в switch выражениях.
    exhaustive_cases: true

    # ???
    # Рекомендует использовать формат TODO(username): для комментариев TODO.
    flutter_style_todos: false

    # Рекомендует использовать валидные паттерны в case блоках.
    invalid_case_patterns: true

    # Рекомендует объединять return с присваиванием
    join_return_with_assignment: true

    # Рекомендует добавлять ведущие переносы строк в многострочных строках.
    leading_newlines_in_multiline_strings: true

    # Рекомендует добавлять аннотации к библиотекам.
    library_annotations: true

    # Рекомендует избегать использования приватных типов в публичном API.
    library_private_types_in_public_api: true

    # Рекомендует избегать строк длиннее 80 символов.
    lines_longer_than_80_chars: true

    # Рекомендует избегать булевых выражений, состоящих только из литералов.
    literal_only_boolean_expressions: true

    # Рекомендует использовать совпадающие параметры суперкласса.
    matching_super_parameters: true

    # Рекомендует указывать язык для блоков кода в документации.
    missing_code_block_language_in_doc_comment: true

    # Рекомендует добавлять пробелы между смежными строками.
    missing_whitespace_between_adjacent_strings: true

    # Рекомендует избегать default case в switch на перечислениях.
    no_default_cases: true

    # Рекомендует избегать ведущих подчеркиваний в префиксах библиотек.
    no_leading_underscores_for_library_prefixes: true

    # Рекомендует избегать ведущих подчеркиваний в локальных идентификаторах.
    no_leading_underscores_for_local_identifiers: true

    # Рекомендует избегать сравнений с булевыми литералами.
    no_literal_bool_comparisons: true

    # Рекомендует избегать no-op операций с примитивами.
    noop_primitive_operations: true

    # Рекомендует избегать проверок на null для nullable параметров типов.
    null_check_on_nullable_type_parameter: true

    # Рекомендует избегать null замыканий.
    null_closures: true

    # ???
    # Рекомендует избегать абстрактных классов с одним членом.
    one_member_abstracts: false

    # Рекомендует выбрасывать только Error и его подклассы, не Exception.
    only_throw_errors: true

    # ???
    # Рекомендует избегать переопределения полей.
    overridden_fields: false

    # ???
    # Рекомендует использовать префикс пакета в именах библиотек.
    package_prefixed_library_names: true

    # Рекомендует избегать присваиваний параметрам.
    parameter_assignments: true

    # Рекомендует использовать двойные кавычки для строк.
    prefer_double_quotes: false

    # Рекомендует избегать пустых блоков else.
    avoid_empty_else: true

    # Избегать использования оператора print в продакшен-коде.
    avoid_print: true

    # Не требовать вынесения тел управляющих структур на новую строку.
    always_put_control_body_on_new_line: false

    # Рекомендует размещать обязательные именованные параметры перед необязательными.
    always_put_required_named_parameters_first: true

    # Всегда указывать типы возвращаемых значений для методов и функций.
    always_declare_return_types: true

    # Разрешить относительные импорты файлов в директории 'lib'.
    always_use_package_imports: false

    # Предпочитать относительные импорты перед абсолютными.
    prefer_relative_imports: true

    # Отменять подписки при выходе из виджета или страницы.
    cancel_subscriptions: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "*.freezed.dart"
    - "*.config.dart"
    - "*.gr.dart"
